# Site settings
title: Introducci처n a UNIX - 2017
email: rdanielmillan@gmail.com
description: > # introducci처n a unix
 Electiva N째 182 Introducci처n a UNIX
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# baseurl: /R-2017

# Build settings
markdown: kramdown
show_drafts: FALSE
plugins_dir: _plugins
exclude: ["gulp", '*.org', '*feed*', 'Gemfile*']

# theme: jekyll-theme-minimal
